### ISSUE TITLE
Error while creating with Node[16.*]

### ISSUE THREAD

**Issue by TusharShahi** [gregrickaby/nextjs-github-pages#21]
While deploying with github actions :

````
 /usr/bin/git push origin gh-pages
  warning: url contains a newline in its host component: https://x-access-token:***
````

**Comment by gregrickaby** [comment]
🤔  I just updated the `deploy.yml` to use Node 16 (lts/*) and it worked on the first try:

https://github.com/gregrickaby/nextjs-github-pages/runs/5029030708?check_suite_focus=true

```yml
name: Deploy to Github Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Build
        run: |
          npm i
          npm run build
          npm run export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./out
```
