### ISSUE TITLE
No `/out` folder is created when usign Github Actions

### ISSUE THREAD

**Issue by xtanion** [gregrickaby/nextjs-github-pages#57]
I tried printing the files/folders after the next build in github actions. I get the following result:
```0s
Run ls -a
.
..
.eslintrc.json
.git
.github
.gitignore
.next
README.md
next-env.d.ts
next.config.js
next.config.mjs
node_modules
package-lock.json
package.json
postcss.config.js
public
src
tailwind.config.ts
tsconfig.json```
There is no `/out` folder created, However, when running on my local machine, it works just fine. Can anyone please help me with this?

**Comment by piantino** [comment]
@xtanion I solve this problem remove this part:

```
- name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          # Automatically inject basePath in your Next.js configuration file and disable
          # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
          #
          # You may remove this line if you want to manage the configuration yourself.
          static_site_generator: next
```
This was inject wrong parameters for this version of Nextjs:

```
 ⚠ Invalid next.config.js options detected: 
 ⚠     Unrecognized key(s) in object: 'images' at "experimental"
```
But the next.config.mjs must have: output, images and basePath parameters:

```
/** @type {import('next').NextConfig} */
const nextConfig = {
    output: 'export',
    images: {
        unoptimized: true
    },
    basePath: "/"
};

export default nextConfig;
```
